apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: employee-db
  namespace: microservices
spec:
  serviceName: employee-db
  replicas: 1
  selector:
    matchLabels:
      app: employee-db
  template:
    metadata:
      labels:
        app: employee-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          env:
            - name: POSTGRES_DB
              value: employee_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: employee-data
      volumes:
        - name: employee-data
          persistentVolumeClaim:
            claimName: employee-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: employee-db
  namespace: microservices
spec:
  clusterIP: None
  selector:
    app: employee-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
